### ISSUE TITLE
Problems in Getting real and imag. dielectric function data.

### ISSUE THREAD

**Issue by iamcqlin** [usnistgov/jarvis#149]
Hi everyone.

I'm a newbie to using Jarvis.I have encountered some problems.I want to use this code to get the dielectric matrix.
https://github.com/usnistgov/jarvis/blob/master/jarvis/io/vasp/outputs.py
dielectric_loptics

When I use vasp.5.4.1 the code to extract the data works, but when I use vasp.5.4.4 an error occurs.

It shows :
Traceback (most recent call last):
    real, imag = self.dielectric_loptics
  File "/home/***/anaconda3/lib/python3.8/site-packages/jarvis/io/vasp/outputs.py", line 1130, in dielectric_loptics
    tmp = self.ionic_steps[-1]["dielectricfunction"]["real"]["array"][
TypeError: list indices must be integers or slices, not str

Could anyone help me how I should solve this problem?
Thank you all!

Lin

**Comment by knc6** [comment]
Hi @iamcqlin ,

Thank you for bringing this issue up.

You are right, the issue is mainly due to updated VASP output formats. We have fixed the io/vasp/outputs.py module which should potentially work for both older and newer versions of VASP. 

Please upgrade JARVIS-tools, pip install -U jarvis-tools, and let me know if the issue persists with the new implementation.

Best,

**Comment by iamcqlin** [comment]
Hi ！

Thank you very much！ 
It worked very well.

Lin
